-- Sales Data Analysis using SQL

SELECT SUM(QUANTITY * PRICE) AS TOTAL_SALES
FROM SALES;

SELECT CATEGORY, SUM(QUANTITY * PRICE) AS REVENUE
FROM SALES
GROUP BY CATEGORY;

SELECT PRODUCT, SUM(QUANTITY) AS TOTAL_SOLD
FROM SALES
GROUP BY PRODUCT
ORDER BY TOTAL_SOLD DESC
LIMIT 5;

SELECT REGION, SUM(QUANTITY * PRICE) AS REVENUE
FROM SALES
GROUP BY REGION;
